### PR TITLE
UnoJoy Car Simulator Wheel

### PR DESCRIPTION
**Pull request by cmavc**
an improvement of the unojoy project by using an IMU sensor

### CODE REVIEW

**Comment by iVario-Controller** [comment]
uunojoy it's compatible on ps4 console?

**Comment by cmavc** [comment]
> uunojoy it's compatible on ps4 console?

No its not, but you can use your old ps2 ps1 controller with ps2lib on arduino along with unojoy to play pc games with ps2 controller.

**Comment by gabysantof** [comment]
Is posible to have 4 controllers using arduino mega? I use the "megajoy" and we have a Lot of buttons and analogs inputs on each controllers. So I think that should be cool to have 4 controllers with 14 digital inputs and 2 analogs inputs each one. ( Sorry my english. im from Argentina)

**Comment by cmavc** [comment]
> Is posible to have 4 controllers using arduino mega? I use the "megajoy" and we have a Lot of buttons and analogs inputs on each controllers. So I think that should be cool to have 4 controllers with 14 digital inputs and 2 analogs inputs each one. ( Sorry my english. im from Argentina)

Your english is fine do not worry :) Unfortunatelly this project creates a single Joystick device, therefore you can pick whichever input you want but you'll get a single device at the end.

**Comment by shourya-arnold** [comment]
is unojoy steering wheel is compatible with ps3 and like what is the button layout please reply

**Review by AlanChatham — APPROVED** [review]
Thanks so much for adding this! I definitely abandoned this project for a long time, but I'm glad that you've had success with the project, and I'm super grateful for you to push some code and help clean up the readme a little!

**Pull request merged**
